export const FETCH_SALE_LIST = 'FETCH_SALE_LIST';
export const ADD_ITEM_CART = 'ADD_ITEM_CART';
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const SORT_BY_MIN = 'SORT_BY_MIN';
export const SORT_BY_MAX = 'SORT_BY_MAX';
export const SORT_BY_MANUFACTURER = 'SORT_BY_MANUFACTURER';
export const SORT_BY_MANUFACTURER_REVERSE = 'SORT_BY_MANUFACTURER_REVERSE';
