name: CI

on:
  pull_request:
    branches: develop

jobs:
  firebase-deploy-master:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        node-version: '10.x'
    - run: npm install
    - run: npm run-script build
    - uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting:develop
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

